
title: Mihail Fedorov
url: 'https://mihail.fedorov.net'
baseurl: 'https://mihail.fedorov.net'


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Mihail Fedorov
tagline: DevOps / Sysadmin
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
