title: "Mihail Fedorov - personal webspace"
url: "https://fedorov.net"
baseurl: ""
timezone: Europe/Moscow

include: ["_pages","_"]
exclude: ["_obsolete"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"
      permalink: "/blog/:year/:slug/"

repository: kolobus/kolobus.github.io

gems:
  - jekyll-redirect-from
