url: "https://fedorov.net"
baseurl: ""
timezone: Europe/Moscow

# Seo stuff
title: "Mihail Fedorov - personal webspace"
description: "Personal webspace of Mihail Fedorov. Resume, portfolio, projects, ideas, contacts."
logo: /assets/img/share.jpg

# Author (me)
mail: mihail@fedorov.net
twitter:
  username: 2mf
money:
  bitcoin: 16thToGgBCPgB8frBk3HueJhPjUvv1zGpo
  komodo: RFAtYK9xn2CFF933ev2R1Adu9zwXawQocp
  wirelesscoin: RFAtYK9xn2CFF933ev2R1Adu9zwXawQocp

include: ["_pages"]
exclude: ["_obsolete"]

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/shared.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"
      permalink: "/blog/:year/:slug/"

repository: kolobus/kolobus.github.io

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
