title: "Mihail Fedorov - personal webspace"
url: "https://fedorov.net"
baseurl: "https://fedorov.net"

timezone: Europe/Moscow
include: ["_pages","_"]

# Deafults front-matter

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"
      permalink: "/blog/:year/:slug/"
