title: "Mihail Fedorov - personal webspace"
url: "https://fedorov.net"
baseurl: ""
timezone: Europe/Moscow
include: ["_pages"]
keep_files: ["_"]

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      layout: "post"
      permalink: "/blog/:year/:slug/"
