title: "Mihail Fedorov - personal webspace"
url: "https://fedorov.net"
baseurl: "https://fedorov.net"

timezone: Europe/Moscow
include: ["_pages"]

# Deafults fron-matter

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      comments: "true"
      layout: "post"
